services:
  reth0:
    image: ghcr.io/paradigmxyz/reth:v1.4.1
    container_name: reth0
    volumes:
      - ./rethdata/0:/data/reth/execution-data
      - ./assets:/root/assets/
      - ./ipc/0:/root/ipc
    ports:
      - "8545:8545"
      - "9100:9001"
      - "30303:30303"
      - "30303:30303/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "-d"
      - "--datadir=/data/reth/execution-data"
      - "--chain=/root/assets/genesis.json"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=30303"
      - "--port=30303"
      # Engine API over IPC (if supported by EL)
      - "--auth-ipc"
      - "--auth-ipc.path=/root/ipc/engine.ipc"

  reth1:
    image: ghcr.io/paradigmxyz/reth:v1.4.1
    container_name: reth1
    volumes:
      - ./rethdata/1:/data/reth/execution-data
      - ./assets:/root/assets/
      - ./ipc/1:/root/ipc
    ports:
      - "18545:8545"
      - "9101:9001"
      - "40303:40303"
      - "40303:40303/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "-d"
      - "--datadir=/data/reth/execution-data"
      - "--chain=/root/assets/genesis.json"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=40303"
      - "--port=40303"
      - "--auth-ipc"
      - "--auth-ipc.path=/root/ipc/engine.ipc"

  reth2:
    image: ghcr.io/paradigmxyz/reth:v1.4.1
    container_name: reth2
    volumes:
      - ./rethdata/2:/data/reth/execution-data
      - ./assets:/root/assets/
      - ./ipc/2:/root/ipc
    ports:
      - "28545:8545"
      - "9102:9001"
      - "50303:50303"
      - "50303:50303/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "-d"
      - "--datadir=/data/reth/execution-data"
      - "--chain=/root/assets/genesis.json"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=50303"
      - "--port=50303"
      - "--auth-ipc"
      - "--auth-ipc.path=/root/ipc/engine.ipc"

  prometheus:
    image: prom/prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/data-prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-oss
    user: "501"
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./monitoring/data-grafana:/var/lib/grafana
      - ./monitoring/config-grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/config-grafana/grafana.ini:/etc/grafana/grafana.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      GF_LOG_LEVEL: info
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_BASIC_ENABLED: false
