services:
  load-reth0:
    image: ${LOAD_RETH_IMAGE:-docker.io/loadnetwork/load-reth:v0.1.2}
    container_name: load-reth0
    volumes:
      - ./rethdata/0:/data/load-reth
      - ./assets:/assets
      - ./ipc/0:/ipc
    ports:
      - "8545:8545"
      - "9100:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      ultra_net:
        ipv4_address: 10.250.42.20
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "-d"
      - "--datadir=/data/load-reth"
      - "--chain=/assets/genesis.json"
      - "--engine.persistence-threshold=0"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=30303"
      - "--port=30303"
      - "--auth-ipc"
      - "--auth-ipc.path=/ipc/engine.ipc"
      - "--p2p-secret-key=/assets/p2p-keys/reth0.key"
      - "--nat=extip:10.250.42.20"
      - "--bootnodes=enode://db1e946e73dc3781bf8a3437b21dfeae0388aec45b2e1dc632c7088b98842897d58c08f73209f851a68661b2f8daadbaf3f4d48bc0513073104b67c0f71101c7@10.250.42.21:40303,enode://f1a8ab5d2068e0c16f541e2190b19d15b62b0bcc9daae707b69a6de1e30dbfc52b3a187ab36ca6ef65f400a0f69a2f98a59b85db1b223d1f575b29bf9af0767c@10.250.42.22:50303"
    healthcheck:
      test: ["CMD-SHELL", "test -S /ipc/engine.ipc"]
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 2s

  load-reth1:
    image: ${LOAD_RETH_IMAGE:-docker.io/loadnetwork/load-reth:v0.1.2}
    container_name: load-reth1
    volumes:
      - ./rethdata/1:/data/load-reth
      - ./assets:/assets
      - ./ipc/1:/ipc
    ports:
      - "18545:8545"
      - "9101:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      ultra_net:
        ipv4_address: 10.250.42.21
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "-d"
      - "--datadir=/data/load-reth"
      - "--chain=/assets/genesis.json"
      - "--engine.persistence-threshold=0"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=40303"
      - "--port=40303"
      - "--auth-ipc"
      - "--auth-ipc.path=/ipc/engine.ipc"
      - "--p2p-secret-key=/assets/p2p-keys/reth1.key"
      - "--nat=extip:10.250.42.21"
      - "--bootnodes=enode://e0ca607db1c230a1587402e5f92e9aa71a9d94306745c12fa9014885c65bd3a7a81902eda068d8c27514a28cdae633bb5047a029b36f9f73649cce1b125d2edf@10.250.42.20:30303,enode://f1a8ab5d2068e0c16f541e2190b19d15b62b0bcc9daae707b69a6de1e30dbfc52b3a187ab36ca6ef65f400a0f69a2f98a59b85db1b223d1f575b29bf9af0767c@10.250.42.22:50303"
    healthcheck:
      test: ["CMD-SHELL", "test -S /ipc/engine.ipc"]
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 2s

  load-reth2:
    image: ${LOAD_RETH_IMAGE:-docker.io/loadnetwork/load-reth:v0.1.2}
    container_name: load-reth2
    volumes:
      - ./rethdata/2:/data/load-reth
      - ./assets:/assets
      - ./ipc/2:/ipc
    ports:
      - "28545:8545"
      - "9102:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      ultra_net:
        ipv4_address: 10.250.42.22
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "-d"
      - "--datadir=/data/load-reth"
      - "--chain=/assets/genesis.json"
      - "--engine.persistence-threshold=0"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=50303"
      - "--port=50303"
      - "--auth-ipc"
      - "--auth-ipc.path=/ipc/engine.ipc"
      - "--p2p-secret-key=/assets/p2p-keys/reth2.key"
      - "--nat=extip:10.250.42.22"
      - "--bootnodes=enode://e0ca607db1c230a1587402e5f92e9aa71a9d94306745c12fa9014885c65bd3a7a81902eda068d8c27514a28cdae633bb5047a029b36f9f73649cce1b125d2edf@10.250.42.20:30303,enode://db1e946e73dc3781bf8a3437b21dfeae0388aec45b2e1dc632c7088b98842897d58c08f73209f851a68661b2f8daadbaf3f4d48bc0513073104b67c0f71101c7@10.250.42.21:40303"
    healthcheck:
      test: ["CMD-SHELL", "test -S /ipc/engine.ipc"]
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 2s

  # ---------------------------------------------------------------------------
  # Ultramarine (Consensus) nodes using Engine IPC inside Docker
  # Each ultramarine instance mounts its node home under /nodes/N, the matching
  # IPC directory under /ipc, and waits for both the config file and the
  # /ipc/engine.ipc socket before starting. Eth1 JSON-RPC is overridden to the
  # respective load-rethX service inside the Docker network.

  ultramarine0:
    image: ultramarine:local
    container_name: ultramarine0
    depends_on:
      load-reth0:
        condition: service_healthy
    volumes:
      - ./nodes/0:/nodes/0
      - ./ipc/0:/ipc
      - ./assets:/assets:ro
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:29000:29000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      ultra_net:
        ipv4_address: 10.250.42.10
    command:
      - start
      - --home=/nodes/0
      - --engine-ipc-path=/ipc/engine.ipc
      - --execution-genesis-path=/assets/genesis.json
      - --eth1-rpc-url=http://load-reth0:8545

  ultramarine1:
    image: ultramarine:local
    container_name: ultramarine1
    depends_on:
      load-reth1:
        condition: service_healthy
    volumes:
      - ./nodes/1:/nodes/1
      - ./ipc/1:/ipc
      - ./assets:/assets:ro
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:29001:29001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      ultra_net:
        ipv4_address: 10.250.42.11
    command:
      - start
      - --home=/nodes/1
      - --engine-ipc-path=/ipc/engine.ipc
      - --execution-genesis-path=/assets/genesis.json
      - --eth1-rpc-url=http://load-reth1:8545

  ultramarine2:
    image: ultramarine:local
    container_name: ultramarine2
    depends_on:
      load-reth2:
        condition: service_healthy
    volumes:
      - ./nodes/2:/nodes/2
      - ./ipc/2:/ipc
      - ./assets:/assets:ro
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:29002:29002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      ultra_net:
        ipv4_address: 10.250.42.12
    command:
      - start
      - --home=/nodes/2
      - --engine-ipc-path=/ipc/engine.ipc
      - --execution-genesis-path=/assets/genesis.json
      - --eth1-rpc-url=http://load-reth2:8545

  prometheus:
    image: prom/prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ultra_net

  grafana:
    image: grafana/grafana-oss
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/config-grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/config-grafana/grafana.ini:/etc/grafana/grafana.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ultra_net
    environment:
      GF_LOG_LEVEL: info
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards-data/default.json
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_BASIC_ENABLED: false

volumes:
  prometheus_data:
  grafana_data:

networks:
  ultra_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.250.42.0/24
