max_width = 100
comment_width = 100
wrap_comments = true
normalize_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
binop_separator = "Back"
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
newline_style = "Unix"
