
[package]
name = "ultramarine"
description = "A Rust implementation of the Load Network consensus client"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "ultramarine"
path = "src/main.rs"
