[package]
name = "ultramarine"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "A Rust implementation of the Load Network consensus client"

[[bin]]
name = "ultramarine"
path = "src/main.rs"

[dependencies]

color-eyre.workspace = true
tracing.workspace = true
jsonwebtoken = "9.3.1"

# malachite dependencies
malachitebft-app.workspace = true
malachitebft-app-channel.workspace = true
malachitebft-config.workspace = true
malachitebft-core-types.workspace = true
malachitebft-metrics.workspace = true

# ultramarine dependencies
ultramarine-cli.workspace = true
ultramarine-node.workspace = true
ultramarine-types.workspace = true
