name: Docker

on:
  push:
    branches: [main]
    tags: ["v*"]
    paths:
      - "Dockerfile*"
      - ".dockerignore"
      - "Makefile"
      - "bin/**"
      - "crates/**"
      - ".github/workflows/docker.yml"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "Dockerfile*"
      - ".dockerignore"
      - "Makefile"
      - "bin/**"
      - "crates/**"
      - ".github/workflows/docker.yml"

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: loadnetwork/ultramarine

jobs:
  # --------------------------------------------------------------------------
  # PR smoke build (non-draft PRs). Build only; do not push.
  # --------------------------------------------------------------------------
  smoke:
    name: PR Smoke Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        run: make docker-build

  # --------------------------------------------------------------------------
  # Pushes to main and tags — build & push multi-arch images
  # --------------------------------------------------------------------------
  push:
    name: Build & Push
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # If your Makefile uses cross to build static bins before docker build,
      # this installs a prebuilt cross quickly. If not needed, remove this step.
      - name: Install cross (prebuilt)
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      # Optional: cache cargo/target if your Makefile builds on the host
      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2

      - name: Compute tags
        id: meta
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            tag="${GITHUB_REF#refs/tags/}"
            echo "git_tag=${tag}" >> "$GITHUB_OUTPUT"
            echo "print_tag=${tag},latest" >> "$GITHUB_OUTPUT"
          else
            short_sha="$(echo "${GITHUB_SHA}" | cut -c1-12)"
            echo "git_tag=sha-${short_sha}" >> "$GITHUB_OUTPUT"
            echo "print_tag=sha-${short_sha},latest" >> "$GITHUB_OUTPUT"
          fi

      # Makefile target should build multi-arch and push both GIT_TAG and latest
      - name: Build & push (multi-arch)
        run: make docker-build-push-latest
        env:
          DOCKER_IMAGE_NAME: ${{ env.IMAGE_NAME }}
          GIT_TAG: ${{ steps.meta.outputs.git_tag }}

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          format: sarif
          output: trivy-results.sarif

      - name: Upload scan
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
